export const cases=[
 ['misopasta','AH Miso pasta','200 g',1,'verpakking','accepted'],
 ['misopasta','AH Miso pasta soep','500 g',1,'verpakking','rejected'],
 ['paksoi','AH Paksoi','per stuk',500,'g','quantity_unknown'],
 ['paksoi','AH Paksoi','per stuk',1,'stuk','accepted'],
 ['Taco shells','Santa Maria Taco shells','12 stuks',1,'verpakking','accepted'],
 ['Taco shells','Trolli Taco snoep','150 g',1,'verpakking','rejected'],
 ['Taco shells/tortilla’s','Santa Maria Taco shells','12 stuks',1,'verpakking','accepted'],
 ['kokosmelk','Conimex Kokosmelk','400 ml',800,'ml','accepted'],
 ['kokosmelk','Conimex Kokosmelk','400 ml',1,'stuk','accepted'],
 ['kokosmelk','Conimex Kokosmelk','400 ml',500,'g','quantity_unknown'],
 ['peen en uien','Hutspot met rookworst','500 g',1,'verpakking','rejected'],
 ['peen en uien','Jumbo peen en uien','1 kg',1,'kg','accepted'],
 ['knoflook','AH Knoflookboter','125 g',1,'verpakking','rejected'],
 ['sla','AH Slavink','250 g',1,'verpakking','rejected'],
 ['kipfilet','AH Kipfilet','100 g',1,'verpakking','unreviewed'],
 ['kipfilet','AH Kipfilet','500 g',750,'g','accepted'],
 ['Griekse yoghurt','AH Yoghurt naturel','1 l',1,'verpakking','rejected'],
 ['komijn','AH Komijnekaas','500 g',1,'verpakking','rejected'],
 ['molokhia','AH Sperziebonen','500 g',1,'verpakking','rejected'],
 ['eieren','AH Scharreleieren','10 stuks',12,'stuk','accepted'],
 ['geraspte kaas','AH Geraspte kaas','150 g',200,'g','accepted'],
 ['olijfolie extra vierge','Bertolli Olijfolie mild','500 ml',1,'verpakking','rejected'],
].map(([query,name,pack,quantity,unit,expected])=>({item:{query,quantity,unit},product:{name,package:pack},expected}));
